INSERT INTO COMPANY (COMPANY_NAME ,ADDRESS ,TIMING ,CONTACT_NO ,EMAIL) VALUES ('DIPC' ,'B-1103, THE CAPITAL' , '10 AM TO 7 PM' ,1234567890,'dipc@gmail.com');
INSERT INTO COMPANY (COMPANY_NAME ,ADDRESS ,TIMING ,CONTACT_NO ,EMAIL) VALUES ('meditab' ,'B-1103, THE CAPITAL' , '10 AM TO 7 PM' ,1234567890,'dipc@gmail.com');
INSERT INTO COMPANY (COMPANY_NAME ,ADDRESS ,TIMING ,CONTACT_NO ,EMAIL) VALUES ('IT' ,'B-1103, THE CAPITAL' , '10 AM TO 7 PM' ,1234567890,'dipc@gmail.com');


INSERT INTO OFFERS (SERVICE,FK_C) VALUES ('FrontEnd Developer',1);
INSERT INTO OFFERS (SERVICE,FK_C) VALUES ('BackEnd Developer',1);
INSERT INTO OFFERS (SERVICE,FK_C) VALUES ('Designing',2);