CREATE TABLE COMPANY(

    C_ID INTEGER NOT NULL AUTO_INCREMENT,
    COMPANY_NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    TIMING VARCHAR(255) NOT NULL,
    CONTACT_NO INTEGER NOT NULL,
    EMAIL VARCHAR(255) ,
--    FK_O INTEGER,
--    FOREIGN KEY (FK_O) REFERENCES OFFERS(O_ID),
    PRIMARY KEY (C_ID)
);

CREATE TABLE OFFERS(
    O_ID INTEGER NOT NULL AUTO_INCREMENT,
    SERVICE VARCHAR(255) NOT NULL,
    FK_C INTEGER,
    PRIMARY KEY (O_ID),
    FOREIGN KEY (FK_C) REFERENCES COMPANY(C_ID)
    );

    --    FK_C INTEGER,
--    FOREIGN KEY (FK_C) REFERENCES COMPANY(C_ID)
